name: lint-build-test
on: workflow_dispatch
jobs:
    lint_the_project:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Adding Dependancies
              run: npm ci
            - name: Run Lint
              run: npm run lint
    Test_the_project:
        needs: lint_the_project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Adding Dependancies
              run: npm ci
            - name: Run Test
              run: npm run test
    Buid_the_project:
        needs: Test_the_project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Adding Dependancies
              run: npm ci
            - name: Run Build
              run: npm run build

            