name: lint-build-test
on:
    pull_request:
        types:
            - opened
    workflow_dispatch:
    push:
      branches:
        - master
jobs:
    lint_the_project:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Adding Dependancies
              run: npm ci
            - name: Run Lint
              run: npm run lint
    Test_the_project:
        needs: lint_the_project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Adding Dependancies
              run: npm ci
            - name: Run Test
              run: npm run test
    Buid_the_project:
        needs: Test_the_project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Adding Dependancies
              run: npm ci
            - name: Run Build
              run: npm run build
            - name: upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dist-files
                path: dist

    Deploy_the_project:
      needs: Buid_the_project
      runs-on: ubuntu-latest
      steps:
        - name: download the artifacts
          uses: actions/download-artifact@v3
          with:
            name: dist-files
        - name: see the content
          run: ls
        - name: Deploy
          run: echo "Deploying the app.."
            

            